/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-05-27 16:00:31 UTC)
 * on 2016-06-16 at 22:23:13 UTC 
 * Modify at your own risk.
 */

package com.appspot.iordanis_mobilezeit.wahlzeitApi;

/**
 * Service definition for WahlzeitApi (v1).
 *
 * <p>
 * A multiclient API for Whalzeit
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link WahlzeitApiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class WahlzeitApi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.22.0 of the wahlzeitApi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://iordanis-mobilezeit.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "wahlzeitApi/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public WahlzeitApi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  WahlzeitApi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the Clients collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code WahlzeitApi wahlzeitApi = new WahlzeitApi(...);}
   *   {@code WahlzeitApi.Clients.List request = wahlzeitApi.clients().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Clients clients() {
    return new Clients();
  }

  /**
   * The "clients" collection of methods.
   */
  public class Clients {

    /**
     * Create a request for the method "clients.create".
     *
     * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
     * parameters, call the {@link Create#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Client}
     * @return the request
     */
    public Create create(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Client content) throws java.io.IOException {
      Create result = new Create(content);
      initialize(result);
      return result;
    }

    public class Create extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Client> {

      private static final String REST_PATH = "clients";

      /**
       * Create a request for the method "clients.create".
       *
       * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
       * optional parameters, call the {@link Create#execute()} method to invoke the remote operation.
       * <p> {@link
       * Create#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Client}
       * @since 1.13
       */
      protected Create(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Client content) {
        super(WahlzeitApi.this, "POST", REST_PATH, content, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Client.class);
      }

      @Override
      public Create setAlt(java.lang.String alt) {
        return (Create) super.setAlt(alt);
      }

      @Override
      public Create setFields(java.lang.String fields) {
        return (Create) super.setFields(fields);
      }

      @Override
      public Create setKey(java.lang.String key) {
        return (Create) super.setKey(key);
      }

      @Override
      public Create setOauthToken(java.lang.String oauthToken) {
        return (Create) super.setOauthToken(oauthToken);
      }

      @Override
      public Create setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Create) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Create setQuotaUser(java.lang.String quotaUser) {
        return (Create) super.setQuotaUser(quotaUser);
      }

      @Override
      public Create setUserIp(java.lang.String userIp) {
        return (Create) super.setUserIp(userIp);
      }

      @Override
      public Create set(String parameterName, Object value) {
        return (Create) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "clients.update".
     *
     * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
     * parameters, call the {@link Update#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Client}
     * @return the request
     */
    public Update update(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Client content) throws java.io.IOException {
      Update result = new Update(content);
      initialize(result);
      return result;
    }

    public class Update extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Client> {

      private static final String REST_PATH = "client";

      /**
       * Create a request for the method "clients.update".
       *
       * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
       * optional parameters, call the {@link Update#execute()} method to invoke the remote operation.
       * <p> {@link
       * Update#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Client}
       * @since 1.13
       */
      protected Update(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Client content) {
        super(WahlzeitApi.this, "PUT", REST_PATH, content, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Client.class);
      }

      @Override
      public Update setAlt(java.lang.String alt) {
        return (Update) super.setAlt(alt);
      }

      @Override
      public Update setFields(java.lang.String fields) {
        return (Update) super.setFields(fields);
      }

      @Override
      public Update setKey(java.lang.String key) {
        return (Update) super.setKey(key);
      }

      @Override
      public Update setOauthToken(java.lang.String oauthToken) {
        return (Update) super.setOauthToken(oauthToken);
      }

      @Override
      public Update setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Update) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Update setQuotaUser(java.lang.String quotaUser) {
        return (Update) super.setQuotaUser(quotaUser);
      }

      @Override
      public Update setUserIp(java.lang.String userIp) {
        return (Update) super.setUserIp(userIp);
      }

      @Override
      public Update set(String parameterName, Object value) {
        return (Update) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Flags collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code WahlzeitApi wahlzeitApi = new WahlzeitApi(...);}
   *   {@code WahlzeitApi.Flags.List request = wahlzeitApi.flags().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Flags flags() {
    return new Flags();
  }

  /**
   * The "flags" collection of methods.
   */
  public class Flags {

    /**
     * Create a request for the method "flags.create".
     *
     * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
     * parameters, call the {@link Create#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCase}
     * @return the request
     */
    public Create create(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCase content) throws java.io.IOException {
      Create result = new Create(content);
      initialize(result);
      return result;
    }

    public class Create extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCase> {

      private static final String REST_PATH = "createPhotoCase";

      /**
       * Create a request for the method "flags.create".
       *
       * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
       * optional parameters, call the {@link Create#execute()} method to invoke the remote operation.
       * <p> {@link
       * Create#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCase}
       * @since 1.13
       */
      protected Create(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCase content) {
        super(WahlzeitApi.this, "POST", REST_PATH, content, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCase.class);
      }

      @Override
      public Create setAlt(java.lang.String alt) {
        return (Create) super.setAlt(alt);
      }

      @Override
      public Create setFields(java.lang.String fields) {
        return (Create) super.setFields(fields);
      }

      @Override
      public Create setKey(java.lang.String key) {
        return (Create) super.setKey(key);
      }

      @Override
      public Create setOauthToken(java.lang.String oauthToken) {
        return (Create) super.setOauthToken(oauthToken);
      }

      @Override
      public Create setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Create) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Create setQuotaUser(java.lang.String quotaUser) {
        return (Create) super.setQuotaUser(quotaUser);
      }

      @Override
      public Create setUserIp(java.lang.String userIp) {
        return (Create) super.setUserIp(userIp);
      }

      @Override
      public Create set(String parameterName, Object value) {
        return (Create) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "flags.list".
     *
     * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
     * parameters, call the {@link List#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public List list() throws java.io.IOException {
      List result = new List();
      initialize(result);
      return result;
    }

    public class List extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCaseCollection> {

      private static final String REST_PATH = "photocase";

      /**
       * Create a request for the method "flags.list".
       *
       * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
       * optional parameters, call the {@link List#execute()} method to invoke the remote operation. <p>
       * {@link List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected List() {
        super(WahlzeitApi.this, "GET", REST_PATH, null, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCaseCollection.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public List setAlt(java.lang.String alt) {
        return (List) super.setAlt(alt);
      }

      @Override
      public List setFields(java.lang.String fields) {
        return (List) super.setFields(fields);
      }

      @Override
      public List setKey(java.lang.String key) {
        return (List) super.setKey(key);
      }

      @Override
      public List setOauthToken(java.lang.String oauthToken) {
        return (List) super.setOauthToken(oauthToken);
      }

      @Override
      public List setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (List) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public List setQuotaUser(java.lang.String quotaUser) {
        return (List) super.setQuotaUser(quotaUser);
      }

      @Override
      public List setUserIp(java.lang.String userIp) {
        return (List) super.setUserIp(userIp);
      }

      @Override
      public List set(String parameterName, Object value) {
        return (List) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "flags.update".
     *
     * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
     * parameters, call the {@link Update#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCase}
     * @return the request
     */
    public Update update(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCase content) throws java.io.IOException {
      Update result = new Update(content);
      initialize(result);
      return result;
    }

    public class Update extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCase> {

      private static final String REST_PATH = "photocase";

      /**
       * Create a request for the method "flags.update".
       *
       * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
       * optional parameters, call the {@link Update#execute()} method to invoke the remote operation.
       * <p> {@link
       * Update#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCase}
       * @since 1.13
       */
      protected Update(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCase content) {
        super(WahlzeitApi.this, "PUT", REST_PATH, content, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.PhotoCase.class);
      }

      @Override
      public Update setAlt(java.lang.String alt) {
        return (Update) super.setAlt(alt);
      }

      @Override
      public Update setFields(java.lang.String fields) {
        return (Update) super.setFields(fields);
      }

      @Override
      public Update setKey(java.lang.String key) {
        return (Update) super.setKey(key);
      }

      @Override
      public Update setOauthToken(java.lang.String oauthToken) {
        return (Update) super.setOauthToken(oauthToken);
      }

      @Override
      public Update setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Update) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Update setQuotaUser(java.lang.String quotaUser) {
        return (Update) super.setQuotaUser(quotaUser);
      }

      @Override
      public Update setUserIp(java.lang.String userIp) {
        return (Update) super.setUserIp(userIp);
      }

      @Override
      public Update set(String parameterName, Object value) {
        return (Update) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Photos collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code WahlzeitApi wahlzeitApi = new WahlzeitApi(...);}
   *   {@code WahlzeitApi.Photos.List request = wahlzeitApi.photos().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Photos photos() {
    return new Photos();
  }

  /**
   * The "photos" collection of methods.
   */
  public class Photos {

    /**
     * Create a request for the method "photos.praise".
     *
     * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
     * parameters, call the {@link Praise#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo}
     * @return the request
     */
    public Praise praise(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo content) throws java.io.IOException {
      Praise result = new Praise(content);
      initialize(result);
      return result;
    }

    public class Praise extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo> {

      private static final String REST_PATH = "praisePhoto";

      /**
       * Create a request for the method "photos.praise".
       *
       * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
       * optional parameters, call the {@link Praise#execute()} method to invoke the remote operation.
       * <p> {@link
       * Praise#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo}
       * @since 1.13
       */
      protected Praise(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo content) {
        super(WahlzeitApi.this, "POST", REST_PATH, content, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo.class);
      }

      @Override
      public Praise setAlt(java.lang.String alt) {
        return (Praise) super.setAlt(alt);
      }

      @Override
      public Praise setFields(java.lang.String fields) {
        return (Praise) super.setFields(fields);
      }

      @Override
      public Praise setKey(java.lang.String key) {
        return (Praise) super.setKey(key);
      }

      @Override
      public Praise setOauthToken(java.lang.String oauthToken) {
        return (Praise) super.setOauthToken(oauthToken);
      }

      @Override
      public Praise setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Praise) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Praise setQuotaUser(java.lang.String quotaUser) {
        return (Praise) super.setQuotaUser(quotaUser);
      }

      @Override
      public Praise setUserIp(java.lang.String userIp) {
        return (Praise) super.setUserIp(userIp);
      }

      @Override
      public Praise set(String parameterName, Object value) {
        return (Praise) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "photos.setStatusAsDeleted".
     *
     * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
     * parameters, call the {@link SetStatusAsDeleted#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo}
     * @return the request
     */
    public SetStatusAsDeleted setStatusAsDeleted(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo content) throws java.io.IOException {
      SetStatusAsDeleted result = new SetStatusAsDeleted(content);
      initialize(result);
      return result;
    }

    public class SetStatusAsDeleted extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo> {

      private static final String REST_PATH = "setStatusAsDeleted";

      /**
       * Create a request for the method "photos.setStatusAsDeleted".
       *
       * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
       * optional parameters, call the {@link SetStatusAsDeleted#execute()} method to invoke the remote
       * operation. <p> {@link SetStatusAsDeleted#initialize(com.google.api.client.googleapis.services.A
       * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo}
       * @since 1.13
       */
      protected SetStatusAsDeleted(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo content) {
        super(WahlzeitApi.this, "POST", REST_PATH, content, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo.class);
      }

      @Override
      public SetStatusAsDeleted setAlt(java.lang.String alt) {
        return (SetStatusAsDeleted) super.setAlt(alt);
      }

      @Override
      public SetStatusAsDeleted setFields(java.lang.String fields) {
        return (SetStatusAsDeleted) super.setFields(fields);
      }

      @Override
      public SetStatusAsDeleted setKey(java.lang.String key) {
        return (SetStatusAsDeleted) super.setKey(key);
      }

      @Override
      public SetStatusAsDeleted setOauthToken(java.lang.String oauthToken) {
        return (SetStatusAsDeleted) super.setOauthToken(oauthToken);
      }

      @Override
      public SetStatusAsDeleted setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (SetStatusAsDeleted) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public SetStatusAsDeleted setQuotaUser(java.lang.String quotaUser) {
        return (SetStatusAsDeleted) super.setQuotaUser(quotaUser);
      }

      @Override
      public SetStatusAsDeleted setUserIp(java.lang.String userIp) {
        return (SetStatusAsDeleted) super.setUserIp(userIp);
      }

      @Override
      public SetStatusAsDeleted set(String parameterName, Object value) {
        return (SetStatusAsDeleted) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "photos.skip".
     *
     * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
     * parameters, call the {@link Skip#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo}
     * @return the request
     */
    public Skip skip(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo content) throws java.io.IOException {
      Skip result = new Skip(content);
      initialize(result);
      return result;
    }

    public class Skip extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo> {

      private static final String REST_PATH = "skipPhoto";

      /**
       * Create a request for the method "photos.skip".
       *
       * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
       * optional parameters, call the {@link Skip#execute()} method to invoke the remote operation. <p>
       * {@link Skip#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo}
       * @since 1.13
       */
      protected Skip(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo content) {
        super(WahlzeitApi.this, "POST", REST_PATH, content, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo.class);
      }

      @Override
      public Skip setAlt(java.lang.String alt) {
        return (Skip) super.setAlt(alt);
      }

      @Override
      public Skip setFields(java.lang.String fields) {
        return (Skip) super.setFields(fields);
      }

      @Override
      public Skip setKey(java.lang.String key) {
        return (Skip) super.setKey(key);
      }

      @Override
      public Skip setOauthToken(java.lang.String oauthToken) {
        return (Skip) super.setOauthToken(oauthToken);
      }

      @Override
      public Skip setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Skip) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Skip setQuotaUser(java.lang.String quotaUser) {
        return (Skip) super.setQuotaUser(quotaUser);
      }

      @Override
      public Skip setUserIp(java.lang.String userIp) {
        return (Skip) super.setUserIp(userIp);
      }

      @Override
      public Skip set(String parameterName, Object value) {
        return (Skip) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "photos.update".
     *
     * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
     * parameters, call the {@link Update#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo}
     * @return the request
     */
    public Update update(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo content) throws java.io.IOException {
      Update result = new Update(content);
      initialize(result);
      return result;
    }

    public class Update extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo> {

      private static final String REST_PATH = "photo";

      /**
       * Create a request for the method "photos.update".
       *
       * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
       * optional parameters, call the {@link Update#execute()} method to invoke the remote operation.
       * <p> {@link
       * Update#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo}
       * @since 1.13
       */
      protected Update(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo content) {
        super(WahlzeitApi.this, "PUT", REST_PATH, content, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo.class);
      }

      @Override
      public Update setAlt(java.lang.String alt) {
        return (Update) super.setAlt(alt);
      }

      @Override
      public Update setFields(java.lang.String fields) {
        return (Update) super.setFields(fields);
      }

      @Override
      public Update setKey(java.lang.String key) {
        return (Update) super.setKey(key);
      }

      @Override
      public Update setOauthToken(java.lang.String oauthToken) {
        return (Update) super.setOauthToken(oauthToken);
      }

      @Override
      public Update setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Update) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Update setQuotaUser(java.lang.String quotaUser) {
        return (Update) super.setQuotaUser(quotaUser);
      }

      @Override
      public Update setUserIp(java.lang.String userIp) {
        return (Update) super.setUserIp(userIp);
      }

      @Override
      public Update set(String parameterName, Object value) {
        return (Update) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "photos.upload".
     *
     * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
     * parameters, call the {@link Upload#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo}
     * @return the request
     */
    public Upload upload(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo content) throws java.io.IOException {
      Upload result = new Upload(content);
      initialize(result);
      return result;
    }

    public class Upload extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo> {

      private static final String REST_PATH = "photos";

      /**
       * Create a request for the method "photos.upload".
       *
       * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
       * optional parameters, call the {@link Upload#execute()} method to invoke the remote operation.
       * <p> {@link
       * Upload#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo}
       * @since 1.13
       */
      protected Upload(com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo content) {
        super(WahlzeitApi.this, "POST", REST_PATH, content, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.Photo.class);
      }

      @Override
      public Upload setAlt(java.lang.String alt) {
        return (Upload) super.setAlt(alt);
      }

      @Override
      public Upload setFields(java.lang.String fields) {
        return (Upload) super.setFields(fields);
      }

      @Override
      public Upload setKey(java.lang.String key) {
        return (Upload) super.setKey(key);
      }

      @Override
      public Upload setOauthToken(java.lang.String oauthToken) {
        return (Upload) super.setOauthToken(oauthToken);
      }

      @Override
      public Upload setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Upload) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Upload setQuotaUser(java.lang.String quotaUser) {
        return (Upload) super.setQuotaUser(quotaUser);
      }

      @Override
      public Upload setUserIp(java.lang.String userIp) {
        return (Upload) super.setUserIp(userIp);
      }

      @Override
      public Upload set(String parameterName, Object value) {
        return (Upload) super.set(parameterName, value);
      }
    }

    /**
     * An accessor for creating requests from the Filter collection.
     *
     * <p>The typical use is:</p>
     * <pre>
     *   {@code WahlzeitApi wahlzeitApi = new WahlzeitApi(...);}
     *   {@code WahlzeitApi.Filter.List request = wahlzeitApi.filter().list(parameters ...)}
     * </pre>
     *
     * @return the resource collection
     */
    public Filter filter() {
      return new Filter();
    }

    /**
     * The "filter" collection of methods.
     */
    public class Filter {

      /**
       * Create a request for the method "filter.list".
       *
       * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
       * parameters, call the {@link List#execute()} method to invoke the remote operation.
       *
       * @return the request
       */
      public List list() throws java.io.IOException {
        List result = new List();
        initialize(result);
        return result;
      }

      public class List extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.CollectionResponsePhoto> {

        private static final String REST_PATH = "filterPhoto";

        /**
         * Create a request for the method "filter.list".
         *
         * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
         * optional parameters, call the {@link List#execute()} method to invoke the remote operation. <p>
         * {@link List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
         * must be called to initialize this instance immediately after invoking the constructor. </p>
         *
         * @since 1.13
         */
        protected List() {
          super(WahlzeitApi.this, "POST", REST_PATH, null, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.CollectionResponsePhoto.class);
        }

        @Override
        public List setAlt(java.lang.String alt) {
          return (List) super.setAlt(alt);
        }

        @Override
        public List setFields(java.lang.String fields) {
          return (List) super.setFields(fields);
        }

        @Override
        public List setKey(java.lang.String key) {
          return (List) super.setKey(key);
        }

        @Override
        public List setOauthToken(java.lang.String oauthToken) {
          return (List) super.setOauthToken(oauthToken);
        }

        @Override
        public List setPrettyPrint(java.lang.Boolean prettyPrint) {
          return (List) super.setPrettyPrint(prettyPrint);
        }

        @Override
        public List setQuotaUser(java.lang.String quotaUser) {
          return (List) super.setQuotaUser(quotaUser);
        }

        @Override
        public List setUserIp(java.lang.String userIp) {
          return (List) super.setUserIp(userIp);
        }

        @com.google.api.client.util.Key
        private java.lang.String haha;

        /**

         */
        public java.lang.String getHaha() {
          return haha;
        }

        public List setHaha(java.lang.String haha) {
          this.haha = haha;
          return this;
        }

        @Override
        public List set(String parameterName, Object value) {
          return (List) super.set(parameterName, value);
        }
      }

    }
    /**
     * An accessor for creating requests from the Pagination collection.
     *
     * <p>The typical use is:</p>
     * <pre>
     *   {@code WahlzeitApi wahlzeitApi = new WahlzeitApi(...);}
     *   {@code WahlzeitApi.Pagination.List request = wahlzeitApi.pagination().list(parameters ...)}
     * </pre>
     *
     * @return the resource collection
     */
    public Pagination pagination() {
      return new Pagination();
    }

    /**
     * The "pagination" collection of methods.
     */
    public class Pagination {

      /**
       * Create a request for the method "pagination.list".
       *
       * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
       * parameters, call the {@link List#execute()} method to invoke the remote operation.
       *
       * @return the request
       */
      public List list() throws java.io.IOException {
        List result = new List();
        initialize(result);
        return result;
      }

      public class List extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.CollectionResponsePhoto> {

        private static final String REST_PATH = "photo";

        /**
         * Create a request for the method "pagination.list".
         *
         * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
         * optional parameters, call the {@link List#execute()} method to invoke the remote operation. <p>
         * {@link List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
         * must be called to initialize this instance immediately after invoking the constructor. </p>
         *
         * @since 1.13
         */
        protected List() {
          super(WahlzeitApi.this, "GET", REST_PATH, null, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.CollectionResponsePhoto.class);
        }

        @Override
        public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
          return super.executeUsingHead();
        }

        @Override
        public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
          return super.buildHttpRequestUsingHead();
        }

        @Override
        public List setAlt(java.lang.String alt) {
          return (List) super.setAlt(alt);
        }

        @Override
        public List setFields(java.lang.String fields) {
          return (List) super.setFields(fields);
        }

        @Override
        public List setKey(java.lang.String key) {
          return (List) super.setKey(key);
        }

        @Override
        public List setOauthToken(java.lang.String oauthToken) {
          return (List) super.setOauthToken(oauthToken);
        }

        @Override
        public List setPrettyPrint(java.lang.Boolean prettyPrint) {
          return (List) super.setPrettyPrint(prettyPrint);
        }

        @Override
        public List setQuotaUser(java.lang.String quotaUser) {
          return (List) super.setQuotaUser(quotaUser);
        }

        @Override
        public List setUserIp(java.lang.String userIp) {
          return (List) super.setUserIp(userIp);
        }

        @com.google.api.client.util.Key
        private java.lang.String cursor;

        /**

         */
        public java.lang.String getCursor() {
          return cursor;
        }

        public List setCursor(java.lang.String cursor) {
          this.cursor = cursor;
          return this;
        }

        @com.google.api.client.util.Key
        private java.lang.String filter;

        /**

         */
        public java.lang.String getFilter() {
          return filter;
        }

        public List setFilter(java.lang.String filter) {
          this.filter = filter;
          return this;
        }

        @com.google.api.client.util.Key
        private java.lang.Integer limit;

        /**

         */
        public java.lang.Integer getLimit() {
          return limit;
        }

        public List setLimit(java.lang.Integer limit) {
          this.limit = limit;
          return this;
        }

        @com.google.api.client.util.Key
        private java.lang.String fromClient;

        /**

         */
        public java.lang.String getFromClient() {
          return fromClient;
        }

        public List setFromClient(java.lang.String fromClient) {
          this.fromClient = fromClient;
          return this;
        }

        @Override
        public List set(String parameterName, Object value) {
          return (List) super.set(parameterName, value);
        }
      }

    }
  }

  /**
   * Create a request for the method "getAbout".
   *
   * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
   * parameters, call the {@link GetAbout#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public GetAbout getAbout() throws java.io.IOException {
    GetAbout result = new GetAbout();
    initialize(result);
    return result;
  }

  public class GetAbout extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.About> {

    private static final String REST_PATH = "about";

    /**
     * Create a request for the method "getAbout".
     *
     * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
     * optional parameters, call the {@link GetAbout#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetAbout#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetAbout() {
      super(WahlzeitApi.this, "GET", REST_PATH, null, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.About.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAbout setAlt(java.lang.String alt) {
      return (GetAbout) super.setAlt(alt);
    }

    @Override
    public GetAbout setFields(java.lang.String fields) {
      return (GetAbout) super.setFields(fields);
    }

    @Override
    public GetAbout setKey(java.lang.String key) {
      return (GetAbout) super.setKey(key);
    }

    @Override
    public GetAbout setOauthToken(java.lang.String oauthToken) {
      return (GetAbout) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAbout setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAbout) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAbout setQuotaUser(java.lang.String quotaUser) {
      return (GetAbout) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAbout setUserIp(java.lang.String userIp) {
      return (GetAbout) super.setUserIp(userIp);
    }

    @Override
    public GetAbout set(String parameterName, Object value) {
      return (GetAbout) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "images".
   *
   * This request holds the parameters needed by the wahlzeitApi server.  After setting any optional
   * parameters, call the {@link Images#execute()} method to invoke the remote operation.
   *
   * @param photoId
   * @return the request
   */
  public Images images(java.lang.String photoId) throws java.io.IOException {
    Images result = new Images(photoId);
    initialize(result);
    return result;
  }

  public class Images extends WahlzeitApiRequest<com.appspot.iordanis_mobilezeit.wahlzeitApi.model.ImageCollection> {

    private static final String REST_PATH = "photos/{photoId}/images";

    /**
     * Create a request for the method "images".
     *
     * This request holds the parameters needed by the the wahlzeitApi server.  After setting any
     * optional parameters, call the {@link Images#execute()} method to invoke the remote operation.
     * <p> {@link
     * Images#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param photoId
     * @since 1.13
     */
    protected Images(java.lang.String photoId) {
      super(WahlzeitApi.this, "GET", REST_PATH, null, com.appspot.iordanis_mobilezeit.wahlzeitApi.model.ImageCollection.class);
      this.photoId = com.google.api.client.util.Preconditions.checkNotNull(photoId, "Required parameter photoId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Images setAlt(java.lang.String alt) {
      return (Images) super.setAlt(alt);
    }

    @Override
    public Images setFields(java.lang.String fields) {
      return (Images) super.setFields(fields);
    }

    @Override
    public Images setKey(java.lang.String key) {
      return (Images) super.setKey(key);
    }

    @Override
    public Images setOauthToken(java.lang.String oauthToken) {
      return (Images) super.setOauthToken(oauthToken);
    }

    @Override
    public Images setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Images) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Images setQuotaUser(java.lang.String quotaUser) {
      return (Images) super.setQuotaUser(quotaUser);
    }

    @Override
    public Images setUserIp(java.lang.String userIp) {
      return (Images) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String photoId;

    /**

     */
    public java.lang.String getPhotoId() {
      return photoId;
    }

    public Images setPhotoId(java.lang.String photoId) {
      this.photoId = photoId;
      return this;
    }

    @Override
    public Images set(String parameterName, Object value) {
      return (Images) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link WahlzeitApi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link WahlzeitApi}. */
    @Override
    public WahlzeitApi build() {
      return new WahlzeitApi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link WahlzeitApiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setWahlzeitApiRequestInitializer(
        WahlzeitApiRequestInitializer wahlzeitapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(wahlzeitapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
